### ISSUE TITLE
Beautiful theme, sadly doesn't support markdown

### ISSUE THREAD

**Issue by dflock** [expalmer/aurora-theme#3]

**Comment by expalmer** [comment]
Hi dude, but we can change it! Let's to add! I will work on it! Thank you for your feedback!

**Comment by dflock** [comment]
What would be ideal, would be supporting the scopes defined by the (extremely popular) [MarkdownEditng](https://packagecontrol.io/packages/MarkdownEditing) add-on - this would get you the most complete markdown support.

Their .tmLanguage files are [all on Github](https://github.com/SublimeText-Markdown/MarkdownEditing/blob/master/Markdown.tmLanguage), as well as example themes that they ship [which use them](https://github.com/SublimeText-Markdown/MarkdownEditing/blob/master/MarkdownEditor-Dark.tmTheme).

**Comment by expalmer** [comment]
Nice! MarkdownEditing is very cool ! I will add this features. Thanks ;)

**Comment by expalmer** [comment]
Hi Man, I think that now we have markdown support! I don't know if the colors look good. What you think ? I only did a copy of markdownEditing :P

**Comment by dflock** [comment]
I think it looks like a great start, thanks! Any minor tweaks can be done via pull requests, if I get time.

**Comment by expalmer** [comment]
Great! Thank you for your help! Let's go to improve Aurora ;)
