### ISSUE TITLE
Black background for classnames with Babel syntax highlighting

### ISSUE THREAD

**Issue by jamwaffles** [expalmer/aurora-theme#5]
> Language: JavaScript
> Set language in Sublime: `JavaScript (Babel)`
> 
> This does **not** occur with the default JavaScript Sublime language, however that doesn't highlight any of the new ES6 stuff.

Not sure if this is intentional or not, but the background colour for classnames in some cases is black, which looks odd: 

![image](https://cloud.githubusercontent.com/assets/800791/7226328/e31546a4-e73f-11e4-9280-7f9c47ffe83c.png)

<kbd>⌥</kbd> + <kbd>⌘</kbd> + <kbd>P</kbd> when the cursor is on `SessionActions` gives me `meta.class.js entity.name.class.js`.

I think it's only for base classes. Inherited classes look different but fine (IMO):

![image](https://cloud.githubusercontent.com/assets/800791/7226426/8fbdbe72-e740-11e4-9518-ab1b1c521341.png)

---

FWIW, the first example doesn't happen due to `export default`; just a class on it's own triggers the black background:

![image](https://cloud.githubusercontent.com/assets/800791/7226442/ae31bb74-e740-11e4-8caa-fc2c0662cee8.png)

**Comment by expalmer** [comment]
I will take a look! Thank you man!

**Comment by expalmer** [comment]
Done! I removed the brackets. I'm going to improve the theme for ES6 like monokai babel.

**Comment by jamwaffles** [comment]
Awesome! It would be great to have all the support Monokai does in Aurora.

**Comment by expalmer** [comment]
\o/ Thank you.
